apiVersion: v1
kind: Service
metadata:
  name: hello-j-service
spec:
  selector:
    app: hello-j
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Assuming your app listens on port 8080
  type: LoadBalancer
