"use client";

import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [messages, setMessages] = useState<string[]>([]);

  const handleClick = () => {
    setMessages([...messages, "Hi Mate!!"]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>
        <p className={styles.description}>
          This is a simple app with a nice layout.
        </p>
        <button className={styles.button} onClick={handleClick}>
          Say Hi!
        </button>
        <div className={styles.messagesContainer}>
          {messages.map((message, index) => (
            <p key={index} className={styles.message}>
              {message}
            </p>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://nextjs.org" target="_blank" rel="noopener noreferrer">
          Made by Gianluca Mannini
        </a>
      </footer>
    </div>
  );
}
